# Streamlit app environment file
# Make sure to keep this in sync with the abstract dependencies in pyproject.toml
name: sf_env
channels:
  - snowflake
dependencies:
  - typer
  - streamlit
  - snowflake-snowpark-python
  - snowflake-ml-python # this is like snowflake[ml] with pip
  - snowflake.core
  - scrapy # not really needed in Streamlit app.
  - transformers
  # THIS IS NOT YET SUPPORTED IN SNOWFLAKE
  # - pip:
  #   - pip
  #   - markdownify # not really needed in Streamlit app.
